### ISSUE TITLE
importance score 

### ISSUE THREAD

**Issue by riyajatar37003** [sramshetty/ShortGPT#5]
does these importance scores make sense ?

[8211428.52734375,
 5057594.07421875,
 3736915.91015625,
 3227586.345703125,
 3689871.533203125,
 3351593.2578125,
 3044111.75,
 2899957.0205078125,
 2688742.900390625,
 2426028.0209960938,
 2433061.6528320312,
 2243200.3950195312,
 2064878.9208984375,
 1991253.4248046875,
 2140301.0810546875,
 2000642.2299804688,
 2041371.0180664062,
 1918713.4189453125,
 2153077.2265625,
 1906909.8125,
 1454954.0717773438,
 1137825.6186523438,
 980444.470703125,
 993320.5024414062,
 853812.5122070312,
 829364.119140625,
 834055.8408203125,
 946702.3803710938,
 1130785.9765625,
 1324971.9921875,
 1355165.20703125,
 4391842.64453125]

this is from ur notebook only. why they are so high

**Comment by riyajatar37003** [comment]
How it comes the same layers index for both mixtral and llama 
25, 27, 24, 26, 28, 29, 23, 22, 21

**Comment by sramshetty** [comment]
Hi @riyajatar37003, yeah these scores are large because I chose not to compute a mean -- rather a [sum of importances](https://github.com/sramshetty/ShortGPT/blob/78d9615fdcae6d90368832bd0a86c49c323549b9/short_gpt/short_llama.py#L146) over the dataset.  As you can imagine, the more samples in the data the larger these values will become.

As for the pruned layer overlap, both models I show have 32 layers and I remove 9. They would likely differ with different models but the reason why layers in those relative positions are pruned is described in the papers. Hope that helps, otherwise I can provide more detail. Thanks!

**Comment by riyajatar37003** [comment]
Thanks
